### ISSUE TITLE
Calibration Testing 

### ISSUE THREAD

**Issue by b-bilko** [b-bilko/Tracking-Turret#26]
Web server response received.
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "web_turret.py", line 16, in thread
    turret = turret_with_config.start(turret)
  File "/home/pi/Tracking-Turret/turret_with_config.py", line 37, in start
    turret.calibrate()
  File "/home/pi/Tracking-Turret/turret.py", line 50, in calibrate
    t_x = self.stepper_x.calibrate(self.micro_pins[0], self.micro_pos[0])
  File "/home/pi/Tracking-Turret/stepper_base.py", line 57, in calibrate
    return threading.Thread(self.__calibrate_run, args=(micro_pin, micro_pos))
  File "/usr/lib/python3.7/threading.py", line 781, in __init__
    assert group is None, "group argument must be None for now"
AssertionError: group argument must be None for now

**Comment by b-bilko** [comment]
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "web_turret.py", line 16, in thread
    turret = turret_with_config.start(turret)
  File "/home/pi/Tracking-Turret/turret_with_config.py", line 37, in start
    turret.calibrate()
  File "/home/pi/Tracking-Turret/turret.py", line 52, in calibrate
    t_x.join()
  File "/usr/lib/python3.7/threading.py", line 1027, in join
    raise RuntimeError("cannot join thread before it is started")
RuntimeError: cannot join thread before it is started

**Comment by b-bilko** [comment]
Calibrating...
127.0.0.1 - - [17/Jun/2021 20:39:23] "GET /ping HTTP/1.1" 200 -
Web server response received.
127.0.0.1 - - [17/Jun/2021 20:39:23] "GET /ping HTTP/1.1" 200 -
Exception in thread Thread-13:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/Tracking-Turret/stepper_base.py", line 62, in __calibrate_run
    GPIO.setup(micro_pin, GPIO.IN)
NameError: name 'GPIO' is not defined
Web server response received.

Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/Tracking-Turret/stepper_base.py", line 62, in __calibrate_run
    GPIO.setup(micro_pin, GPIO.IN)
NameError: name 'GPIO' is not defined
