### ISSUE TITLE
Stepper Motor Lib syntax change

### ISSUE THREAD

**Issue by b-bilko** [b-bilko/Tracking-Turret#7]
Updated with new imports, and throws this error :

Traceback (most recent call last):
  File "/home/pi/Tracking-Turret-Update-Motor-Lib/turret.py", line 294, in <module>
    t = Turret(friendly_mode=False)
  File "/home/pi/Tracking-Turret-Update-Motor-Lib/turret.py", line 252, in __init__
    self.stepper_x = Stepper(self.mh, 1, MOTOR_X_REVERSED)
  File "/home/pi/Tracking-Turret-Update-Motor-Lib/turret.py", line 162, in __init__
    self.motor = hat.getStepper(200, i_motor)
AttributeError: 'MotorKit' object has no attribute 'getStepper'

**Comment by b-bilko** [comment]
Library implementation notes

https://circuitpython.readthedocs.io/projects/motorkit/en/latest/api.html#implementation-notes

Example with more detail on classes: 

https://github.com/adafruit/Adafruit_CircuitPython_MotorKit/blob/master/examples/motorkit_dual_stepper_test.py

**Comment by b-bilko** [comment]
Ran test_stepper.py

Traceback (most recent call last):
  File "/home/pi/TrackingTurret-Motor-Update/test_stepper.py", line 3, in <module>
    import turret
  File "/home/pi/TrackingTurret-Motor-Update/turret.py", line 192
    self.motor.onestep(direction=direction, adafruit_motorkit.stepper.StepperMotor.INTERLEAVE)
                                           ^
SyntaxError: positional argument follows keyword argument

**Comment by b-bilko** [comment]
Ran test_stepper.py


Traceback (most recent call last):
  File "/home/pi/TrackingTurret-Motor-Update/test_stepper.py", line 6, in <module>
    stepper = turret.Stepper(mh, False, False)
  File "/home/pi/TrackingTurret-Motor-Update/turret.py", line 167, in __init__
    self.thread = threading.Thread(self.__loop)
AssertionError: group argument must be None for now

**Comment by b-bilko** [comment]
Traceback (most recent call last):
  File "/home/pi/TrackingTurret-Motor-Update/test_stepper.py", line 9, in <module>
    stepper.step(i)
  File "/home/pi/TrackingTurret-Motor-Update/turret.py", line 190, in step
    direction = adafruit_motorkit.stepper.StepperMotor.FORWARD if (steps > 0) != self.reverse else adafruit_motorkit.stepper.StepperMotor.BACKWARD
AttributeError: module 'adafruit_motorkit' has no attribute 'stepper'

**Comment by b-bilko** [comment]
Traceback (most recent call last):
  File "/home/pi/Tracking-Turret-Update-Motor-Lib/test_stepper.py", line 9, in <module>
    stepper.step(i)
  File "/home/pi/Tracking-Turret-Update-Motor-Lib/turret.py", line 191, in step
    direction = adafruit_motorkit.FORWARD if (steps > 0) != self.reverse else adafruit_motorkit.BACKWARD
AttributeError: module 'adafruit_motorkit' has no attribute 'BACKWARD'

**Comment by b-bilko** [comment]
Traceback (most recent call last):
  File "/home/pi/Tracking-Turret-Update-Motor-Lib/turret.py", line 298, in <module>
    t.motion_detection(show_video=True)
  File "/home/pi/Tracking-Turret-Update-Motor-Lib/turret.py", line 271, in motion_detection
    self.motion_sensor.find_motion(self.__on_motion, self.__on_no_motion, show_video=show_video)
  File "/home/pi/Tracking-Turret-Update-Motor-Lib/turret.py", line 92, in find_motion
    base = self.get_empty_frame()
  File "/home/pi/Tracking-Turret-Update-Motor-Lib/turret.py", line 61, in get_empty_frame
    frame, candidate = self.grab_image()
  File "/home/pi/Tracking-Turret-Update-Motor-Lib/turret.py", line 43, in grab_image
    raise FrameGrabException()
FrameGrabException
